[package]
name = "edio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
tempfile = "3.24.0"

[dev-dependencies]
serial_test = "3.2.0"
